/**
 * ISO 3166-1 alpha-2 → English display names for SMS catalog countries.
 * Used when normalizing external provider catalogs so the UI never shows "NG (NG)".
 */
export const ISO_COUNTRY_NAMES: Record<string, string> = {
  AE: "United Arab Emirates",
  AF: "Afghanistan",
  AO: "Angola",
  AR: "Argentina",
  AT: "Austria",
  AZ: "Azerbaijan",
  BA: "Bosnia and Herzegovina",
  BD: "Bangladesh",
  BE: "Belgium",
  BG: "Bulgaria",
  BO: "Bolivia",
  BR: "Brazil",
  BY: "Belarus",
  CA: "Canada",
  CG: "Congo",
  CH: "Switzerland",
  CI: "Côte d'Ivoire",
  CM: "Cameroon",
  CN: "China",
  CO: "Colombia",
  CR: "Costa Rica",
  CY: "Cyprus",
  CZ: "Czechia",
  DE: "Germany",
  DO: "Dominican Republic",
  DZ: "Algeria",
  EC: "Ecuador",
  EE: "Estonia",
  EG: "Egypt",
  ES: "Spain",
  ET: "Ethiopia",
  FR: "France",
  GB: "United Kingdom",
  GH: "Ghana",
  GM: "Gambia",
  GN: "Guinea",
  GT: "Guatemala",
  HK: "Hong Kong",
  HN: "Honduras",
  HR: "Croatia",
  HT: "Haiti",
  HU: "Hungary",
  ID: "Indonesia",
  IE: "Ireland",
  IL: "Israel",
  IN: "India",
  IQ: "Iraq",
  IR: "Iran",
  IT: "Italy",
  JM: "Jamaica",
  JO: "Jordan",
  JP: "Japan",
  KE: "Kenya",
  KG: "Kyrgyzstan",
  KH: "Cambodia",
  KR: "South Korea",
  KW: "Kuwait",
  KZ: "Kazakhstan",
  LA: "Laos",
  LK: "Sri Lanka",
  LT: "Lithuania",
  LV: "Latvia",
  LY: "Libya",
  MA: "Morocco",
  MD: "Moldova",
  MG: "Madagascar",
  ML: "Mali",
  MM: "Myanmar",
  MN: "Mongolia",
  MO: "Macau",
  MX: "Mexico",
  MY: "Malaysia",
  MZ: "Mozambique",
  NE: "Niger",
  NG: "Nigeria",
  NI: "Nicaragua",
  NL: "Netherlands",
  NP: "Nepal",
  NZ: "New Zealand",
  OM: "Oman",
  PE: "Peru",
  PG: "Papua New Guinea",
  PH: "Philippines",
  PK: "Pakistan",
  PL: "Poland",
  PR: "Puerto Rico",
  PY: "Paraguay",
  RO: "Romania",
  RS: "Serbia",
  RU: "Russia",
  SA: "Saudi Arabia",
  SD: "Sudan",
  SE: "Sweden",
  SI: "Slovenia",
  SN: "Senegal",
  SV: "El Salvador",
  SZ: "Eswatini",
  TD: "Chad",
  TG: "Togo",
  TH: "Thailand",
  TL: "Timor-Leste",
  TN: "Tunisia",
  TR: "Türkiye",
  TT: "Trinidad and Tobago",
  TW: "Taiwan",
  TZ: "Tanzania",
  UA: "Ukraine",
  UG: "Uganda",
  US: "United States",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VE: "Venezuela",
  VN: "Vietnam",
  YE: "Yemen",
  ZA: "South Africa",
  ZW: "Zimbabwe"
};

export function resolveCountryName(countryCode: string): string {
  const code = countryCode.trim().toUpperCase();
  if (!code) return "Unknown";
  return ISO_COUNTRY_NAMES[code] ?? code;
}

/** Unicode regional-indicator flag from ISO alpha-2. */
export function countryFlagEmoji(countryCode: string): string {
  const code = countryCode.trim().toUpperCase();
  if (!/^[A-Z]{2}$/.test(code)) return "🌐";
  const A = 0x1f1e6;
  return String.fromCodePoint(
    A + (code.charCodeAt(0) - 65),
    A + (code.charCodeAt(1) - 65)
  );
}
